fix(stoneintg-564): ignore empty values
redhat-appstudio/integration-service pull request #317
Opened 2023-09-14 15:50 UTC by 14rcole

Previously empty values in the violations graphs were reported as zero.  This is because in order to calculate the percentage of requests meeting our thresholds we divide the "good" requests by the total requests.  If there are no total requests then grafana sets 0/0 to 0 rather than dividing by 0.  This change ignores the empty values and changes the display from a line to bars to improve readability.

## Maintainers will complete the following section

- [ ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
- [ ] Code coverage from testing does not decrease and new code is covered
- [ ] [Controllers diagrams](https://github.com/redhat-appstudio/integration-service/tree/main/docs) are updated when PR changes controllers code  (if applicable)

2023-09-15 09:21 UTC, MartinBasti requested changes
This PR updates one SLO, but we have at least two SLOs

2023-09-15 12:36 UTC, 14rcole commented
Five years and I still can't commit things properly.  Fixed now, I double-checked and I only saw those two SLOs having this issue

2023-09-15 13:03 UTC, MartinBasti approved these changes

2023-09-18 11:05 UTC, jinqi7 approved these changes
LGTM

2023-09-18 13:26 UTC, merged