fix(stoneintg-582): do not requeue SEB if snapshot cannot be found
redhat-appstudio/integration-service pull request #335
Opened 2023-09-26 17:22 UTC by 14rcole

Ordinarilly if the snapshot associated with an SEB cannot be found we fail and requeue the reconciliation for that SEB.  This change adds retries to the retrieval of the Snapshot and does away with the requeue if it cannot be found.  This way if the user deletes a snapshot the SEB will not be permanently stuck in a reconcile state.

## Maintainers will complete the following section

- [ ] Commit messages are descriptive enough ([hints](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/))
- [ ] Code coverage from testing does not decrease and new code is covered
- [ ] [Controllers diagrams](https://github.com/redhat-appstudio/integration-service/tree/main/docs) are updated when PR changes controllers code  (if applicable)

2023-09-29 12:02 UTC, dirgim approved these changes
LGTM

2023-10-02 08:40 UTC, MartinBasti requested changes

2023-10-02 08:40 UTC, MartinBasti commented on controllers/binding/snapshotenvironmentbinding_controller.go
> +		return logger.HandleLoaderError(err, "Snapshot", "SnapshotEnvironmentBinding")
Logger shouldn't have responsibility to decide code flow (yes there is exception in go, for `panic` and `fatal` but that ends everything)

https://github.com/redhat-appstudio/integration-service/pull/329

2023-10-03 13:01 UTC, MartinBasti approved these changes
Thank you

2023-10-03 13:59 UTC, merged